### PR TITLE
Add vundo-save command

### PR DESCRIPTION
**Pull request by ideasman42**
Support saving the buffer at the current state while exploring history.

Implements #58

### CODE REVIEW

**Comment by casouri** [comment]
I would bind it to `[remap save-buffer]` tho. You mentioned that you accidentally saved the vundo buffer when trying to save the buffer right?

**Comment by ideasman42** [comment]
> I would bind it to `[remap save-buffer]` tho. You mentioned that you accidentally saved the vundo buffer when trying to save the buffer right?

Thanks for the hint, I wasn't aware of `remap`, done.

**Comment by ideasman42** [comment]
Any other changes needed? (`remap` is now used)

**Comment by casouri** [comment]
No it's perfect. Merged, thanks for reminding me!

**Pull request closed without merging**
