### PR TITLE
Say "Emacs undo history" in README

### PR DESCRIPTION
**Pull request by szepeviktor**
Some of us may not know what is "undo history".

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider making this change in the top right "About" box.

**Comment by ideasman42** [comment]
Looks like a bot? The change doesn't seem like an improvement.

**Comment by szepeviktor** [comment]
I am human bot 🙃 with few thousand contribution.

After reading the README I had no clue where that undo takes place.

**Comment by casouri** [comment]
FWIW I think the README is clear enough for its target audience.

**Comment by szepeviktor** [comment]
> for its target audience

You are right.

**Pull request closed without merging**
