### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jdtsmith**
Mentioned on reddit so it would be good to bump version for ELPA to
pickup the new diff functionality.

### CODE REVIEW

**Comment by casouri** [comment]
Why 2.5? I thought the next version should be 2.2?

**Comment by jdtsmith** [comment]
Kind of arbitrarily picked based on feature set but happy with whatever you choose.

**Comment by jdtsmith** [comment]
Switched to 2.2 and updated release doc.  I'd suggest merging #86 first.  I think #81 can wait until 2.3.  

BTW at some point are you willing/interested to include a screencast in the README?

**Comment by casouri** [comment]
Merged, thanks!

**Comment by casouri** [comment]
> BTW at some point are you willing/interested to include a screencast in the README?

Yeah why not. I'll find some time to restructure the README a bit in Markdown, since we now have so much more features.

**Comment by jdtsmith** [comment]
Nice.  Currently working on a video thing for Emacs so when that's ready maybe I'll use vundo as its debut example.

**Comment by casouri** [comment]
Looking forward to it :-)

**Pull request closed without merging**
