### PR TITLE
Use ASCII syntax for quoting variable names

### PR DESCRIPTION
**Pull request by phikal**
Not sure if this was intentional or not, but since the quotations were inconsistent, this would revert everything to the conventional syntax.

### CODE REVIEW

**Comment by casouri** [comment]
I thought curly quotes are the new standard syntax?

**Comment by phikal** [comment]
(elisp) Documentation Tips says

     Documentation strings can also use an older single-quoting
     convention, which quotes symbols with grave accent ` and apostrophe
     ': `like-this' rather than ‘like-this’.  This older convention was
     designed for now-obsolete displays in which grave accent and
     apostrophe were mirror images.  Documentation using this convention
     is converted to the user’s preferred format when it is copied into
     a help buffer.

which I didn't actually know about.  This is actually the first time I have seen curved single quotes being used, probably because the older ones are easier to write.  If you don't want this, I can also update the patch to revert the old syntax to curved quotes.

**Comment by casouri** [comment]
I think comments uses the ASCII quotes and we don't need to change it. Honestly I just enable `electric-quote-mode` and let it decide, because IIRC it defaults to the, well, default convention of Emacs.

**Comment by phikal** [comment]
Yuan Fu ***@***.***> writes:

> I think comments uses the ASCII quotes and we don't need to change
> it. Honestly I just enable `electric-quote-mode` and let it decide,
> because IIRC it defaults to the, well, default convention of Emacs.

I actually was not familiar with ‘electric-quote-mode’.  I’d say that
makes these changes superfluous.  Feel free to close the pull request.

-- 
	Philip Kaludercic

**Comment by casouri** [comment]
Cool!

**Comment by casouri** [comment]
Grrrr, ok, I'll change the quotes (and update my configuration and live with mixed quotes in config files and my other packages). I'll do that in like 2 weeks.

**Comment by casouri** [comment]
Pushed the change :-)

**Pull request closed without merging**
