### PR TITLE
Fix #84: correct cleanup regexp and inhibit diff --label

### LINKED ISSUE #84: diff not working in some buffers
Hi,

I have tried vundo, but the diff feature didn't work properly for me. It does work in `init.el` buffer, but it doesn't work in `15.py` - the diff is not shown at all:
EmacsPgU29p

After a bit of digging, I have found that the problem is caused by `vundo-diff--cleanup-diff-buffer` - before it is called, the diff is shown.
Seems like an issue with the regexp:
```elisp
(rx-to-string `(and bol ,pat (+ space)
		    (group (group (+ (not ?\t)))
			   (* any))
		    eol))
```
In particular, when I replace the greedy operators `+` and `*` by their non-greedy variant:
```elisp
(rx-to-string `(and bol ,pat (+ space)
		    (group (group (+? (not ?\t)))
			   (*? any))
		    eol))
```

The diff is shown nicely:
Emacs5eP2WP

I don't know why this only happens in some buffers.

### PR DESCRIPTION
**Pull request by jdtsmith**
Fixes #84.

### CODE REVIEW

**Review by ideasman42 — COMMENTED** [review]
Tested this to work, note, for bug fixes, suggest to use `Fix #84: Invalid regex could cause empty diff content` ... then move anything unrelated into a separate PR.

This makes review smoother as reviewers aren't having to separate functional/non-functional changes... and in the off-chance the cleanup causes a breakage, it makes tracking down the error more straightforward.

**Comment by jdtsmith** [comment]
Thanks, updated PR subject and commit message, and removed what WS changes I could.  Give another test.

**Comment by michael-heerdegen** [comment]
I think in addition you want to replace `space` with `blank`: the former potentially matches line breaks, the latter doesn't.

**Comment by jdtsmith** [comment]
Good spot, fixed. @casouri this should be ready to review/merge.

**Comment by casouri** [comment]
Merged, thanks!

**Pull request merged**
