### PR TITLE
Move to beginning of next stem

### PR DESCRIPTION
**Pull request by 45mg**
To switch branches, one needs to be on a stem root (branchpoint). Add a command to make it easier to move between stem roots (meant to be used along with `vundo-stem-root`).

I don't have FSF papers yet; let me know if you'd be willing to merge this and I'll look into it.

### CODE REVIEW

**Comment by casouri** [comment]
Thanks! Makes sense. Could you bind it to `w` instead? For me `A` is a bit unintuitive since `a` goes backward, then logically `A` should go even more backward rather than forward. `w` is a vim thing but...

**Comment by casouri** [comment]
If you have other ideas, I'm all ears ;-)

**Comment by 45mg** [comment]
Changed it to `w`. Evil users will probably want to redo all the bindings around hjkl anyway.

I've sent a mail to emacs-devel.

**Comment by casouri** [comment]
Merged, thanks!

**Comment by casouri** [comment]
Also thanks for initializing on the copyright process. I hope this can be your first step to more awesome Emacs contribution!

**Pull request closed without merging**
